locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail')
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower
import uuid      #required for unique book instances


# Create your models here.
class Genre(models.Model):
    """model representing a book"""
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter a book genre (e.g. science fiction, french poetry etc.)"
    )

    def __str__(self):
        return self.name
    
    def get_absolute(self):
        """returns the url to access a particular genre instance."""
        return reverse('genre-detail', args=[str(self.id)])
    
    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                 name='genre_name_case_insensitive_unique',
                violation_error_message='genre already exists (case insensitive match)'
            )
        ]

class Language(models.Model):
    name = models.CharField(max_length=100, unique=True, help_text="enter the book's original languae")

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('language-detail', args=[str(self.id)])

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                 name='language_name_case_insensitive_unique',
                violation_error_message='genre already exists (case insensitive match)'
            )
        ]

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True)
    summary = models.TextField(max_length=1000, help_text='enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True, help_text='13 character <a href="https://www.isbn-international.org/content/what-isbn''">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='select a genre for this book')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        """create a string for the genre. this is required to diplay genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'
    
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='unique id for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability'
    )

    class Meta:
        ordering = ['due_back']
    
    def __str__(self):
        return f'{self.id} ({self.book.title})'
    
    def display_book(self):
        """create a string for the genre. this is required to diplay genre in Admin."""
        return ', '.join(book.book for book in self.book.all()[:3])
    
    display_book.short_description = 'Book'

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']
    
    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])
    
    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

locallibrary/catalog/views.py
from django.shortcuts import render
from .models import Book, Author, BookInstance, Genre
from django.views import generic

# Create your views here.
def index(request):
    """view function for home page of site"""

    # generate counts of some of the main objects
    num_books = Book.objects.all().count()

    # Number of visit to this view is counted in the session
    num_visits = request.session.get('num_visits', 0)
    num_visits += 1
    request.session['num_visits'] = num_visits

    num_instances = BookInstance.objects.all().count

    # available books (status = 'a)
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # the all() is applied by default
    num_authors = Author.objects.count()

    words_in_genre = Genre.objects.filter(name__exact='Thriller').count()
    words_in_books = Book.objects.filter(title__exact='hard').count()


    # dynamic page title
    page_title = 'Abuja Local Library'

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'words_in_books': words_in_books,
        'words_in_genre': words_in_genre,
        'page_title': page_title,
        'num_visits': num_visits,
    }

    # render the html template index.html with the data in the context available
    return render(request, 'index.html', context)

class BookListView(generic.ListView):
    model = Book


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

locallibrary/catalog/templates/base_generic.html
<!doctype html>
<html lang="en">
    <head>
        {% block title %}
            <title>{{ title }}</title>
        {% endblock %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
        crossorigin="anonymous">
        <!-- Add additional CSS in static file -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %}
                        <ul class="sidebar-nav">
                            <li><a href="{% url 'index' %}">Home</a></li>
                            <li><a href="{% url 'books' %}">All books</a></li>
                            <li><a href="{% url 'authors' %}">All authors</a></li>
                        </ul>
                    {% endblock %}
                </div>
                <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
            </div>
        </div>
    </body>
</html>

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Author: {{ author }} </h1>
    <p>{{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Books</h4>

        <dl>
            {% for book in author.book_set.all %}
                <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</dt>
                <dd>{{book.summary}}</dd>
            {% empty %}
                <p>This author has no books.</p>
            {% endfor %}
        </dl>

    </div>
{% endblock %}

{% block sidebar %}
    {{ block.super }}

    {% if perms.catalog.change_author or perms.catalog.delete_author %}
        <hr>
        <ul class="sidebar-nav">
            {% if perms.catalog.change_author %}
                <li><a href="{% url 'author-detail' author.id %}">Update author</a></li>
            {% endif %}
            {% if not author.book_set.all and perms.catalog.delete_author %}
                <li><a href="{% url 'author-delete' author.id %}">Delete author</a></li>
            {% endif %}
        </ul>
    {% endif %}

{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author List</h1>
    {% if author_list %}
        <ul>
            {% for author in author_list %}
                <li>
                    <a href="{{ author.get_absolute_url }}">{{ author.first_name }}, {{ author.last_name}} ({{ author.date_of_birth}})</a>
                    <!-- ({{ book.author }}) -->
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no authors in the library.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>

    <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p>
    <!-- author detail link not yet defined -->
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Copies</h4>

        {% for copy in book.bookinstance_set.all %}
            <hr />
            <p
                class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
                <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
            {% endif %}
                <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
                <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
                    ({{ book.author }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Local Library Home</h1>
    <p>
        Welcome to LocalLibrary, a website developed by
        <em>Mozilla Developer Network</em>!
    </p>
    <h2>Dynamic content</h2>
    <p>The library has the following record counts:</p>
    <ul>
        <li><strong>Books:</strong> {{ num_books }}</li>
        <li><strong>Copies:</strong> {{ num_instances }}</li>
        <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
        <li><strong>Authors:</strong> {{ num_authors }}</li>
        <li><strong>Hard in Books:</strong> {{ words_in_books }}</li>
        <li><strong>thriller in genre:</strong> {{ words_in_genre }}</li>
    </ul>

    <p>
        You have visited this page {{ num_visits }} time {{ num_visits|pluralize }}
    </p>
{% endblock %}